Repository Dev-tanay/Rubik-Cube, pull requests merged in 2024-07, with the labels that each got.

#342 Improved the UI and Conformation pop-up
  edit-profile.html
  profile.css
  profile.js
Labels: gssoc, level1

#350 Improved UI to match website theme
  check-progress.html
  progress.css
Labels: gssoc, level1

#353 Profile icon and music button now visible
  style.css
Labels: gssoc, level1

#335 change some text and color
  index.html
  profile.css
Labels: level1, ssoc

#287 Added shortcut keys
  README.md
  script.js
Labels: level1, ssoc

#234 added a How to Play dropdown
  changeview.png
  index.html
  style.css
  twist1.png
  twist2.png
Labels: level1, ssoc

#358 Add Email and Additional Profile Info Fields
  edit-profile.html
  profile.js
Labels: gssoc, level1

#366 Edit: the about us page linked correctly
  check-progress.html
  index.html
Labels: gssoc, level1

#348 Enhancing progress page
  check-progress.html
  progress.css
Labels: gssoc, level1

#290 Improved the UI of the buttons
  AboutUs/About.css
  style.css
Labels: gssoc, level1

#230 NavBar added
  index.html
  style.css
Labels: gssoc, level1

#156 [DOCS] : Adding a Installation and Setup Guide.
  README.md
Labels: gssoc

#214 Contributor's Logo and Addition of Preloader
  README.md
  index.html
Labels: gssoc, level1

#197 change in cursor:pointer in style.css
  index.html
  script.js
  style.css
Labels: gssoc, level1

#191 Added Restart button
  index.html
  script.js
  style.css
Labels: gssoc, level1

#34 added feature to switch between dark and light theme
  images/BulpOff.png
  images/BulpOn.png
  index.html
  script.js
  style.css
Labels: gssoc, level2

#369 add dockerfile and kubernetes file
  Dockerfile
  deployment.yaml
  service.yaml
Labels: gssoc, level1

#181 Enhanced a Timer feature in the game
  index.html
  script.js
  style.css
Labels: gssoc, level1

#178 added about page
  AboutPage.html
  index.html
  style.css
  styleAbout.css
Labels: gssoc, level1
