Repository Dev-tanay/Rubik-Cube, pull requests merged in 2024-06, with the labels that each got.

#227 #218 Enhancing User Experience with Subtle Background Music
  Music/8 Bit Space Groove! Chill Pretty Chiptune Game Music by HeatleyBros.mp3
  index.html
  script.js
  style.css
Labels: level1, ssoc

#222 Adding Try Again Option #201
  script.js
Labels: gssoc, level1

#162 Added an About Page
  about.css
  about.html
  index.html
  package-lock.json
  style.css
Labels: gssoc, level1

#258 Responsive Design Added
  index.html
  script1.js
  style.css
Labels: level1, ssoc

#255 Update About Page Typography/Font Size
  about.css
  about.html
Labels: gssoc, level1, ssoc

#262 Revert "Responsive Design Added "
  index.html
  script1.js
  style.css
Labels: level1, ssoc

#265 Adding Images, Recognizing Contributors, and Mentioning GitHub Repository in the "About Us" Section #259
  AboutUs/About.css
  AboutUs/About.html
  AboutUs/About.js
  AboutUs/AboutUs_images/AboutUsBanner.png
  index.html
  script1.js
  style.css
Labels: level1, ssoc

#288 Issue#278 fixed. Double scroll removed.
  AboutUs/About.css
Labels: gssoc, level1

#291 chore: add issue and pr workflows
  .github/ISSUE TEMPLATE/Bug_report_template.md
  .github/ISSUE TEMPLATE/Feature_request_template.md
  .github/ISSUE TEMPLATE/docs.md
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/document.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/ISSUE_TEMPLATE/other.yml
  .github/pull_request_template.yml
Labels: gssoc, level1

#292 Update bug.yml
  .github/ISSUE_TEMPLATE/bug.yml
Labels: gssoc

#297 Added User profile section and also added check progress section in profile dropdown
  check-progress.html
  edit-profile.html
  images/profilepic.jpg
  index.html
  profile.css
  profile.js
  progress.css
  progress.js
  style.css
Labels: gssoc, level1

#295 Dynamic Copyright Year Done
  AboutUs/About.html
Labels: ssoc

#303 BACKGROUND THEME CHANGE
  index.html
  script.js
  style.css
Labels: gssoc, level1

#298 Added keys for moves(R,L,U,D,B,F) and rotation (arrow keys)
  README.md
  script.js
Labels: level1, ssoc

#282 [Enhancement]: Enabling cube rotation via 'right-click-drag' # 277
  script.js
Labels: level1, ssoc

#315 Dummy values in check progress page corrected
  check-progress.html
  progress.css
  progress.js
Labels: level1, ssoc

#317 Add Control Functions with Keyboard Keys #152
  index.html
  script.js
  script1.js
  style.css
Labels: gssoc, level1

#327 Exit button fixed
  check-progress.html
  index.html
Labels: level1, ssoc

#337 Update 2 settings Option
  index.html
Labels: gssoc, level1

#336 Updated profile page
  .vscode/settings.json
  profile.css
  progress.css
Labels: level1, ssoc

#341 fixed responsiveness and also fixed the website not working
  index.html
  script.js
  style.css
Labels: gssoc, level1

#340 [Feature] Add Styles on Scrollbar in About page
  AboutUs/About.css
Labels: level1, ssoc

#338 Added Social Media icons
  AboutUs/About.css
  AboutUs/About.html
Labels: gssoc, level1
